#!/usr/bin/perl -w

use strict;
use warnings;
use feature qw( switch );

use Term::ANSIColor;
use Cwd;

my $arch = `uname -m`;
chomp($arch);

print colored("Found ARCH: $arch \n", "cyan");

my $cwd = getcwd();
given ($cwd) {
	when ('/var/smoothwall/mods-available/gkrellmd') {
		print colored("CWD: $cwd\n", "cyan");
	}
	when ('/root/swe-gkrellmd') {
		# dev mode ?
		print colored("It looks like you are in the dev directory.  \n", "cyan"); 
		print colored("Would you like to install this mod to your smoothie?  \n", "cyan");
		my $ans = readline();
		chomp($ans);
		if ($ans =~ /[Yy](?:es)?/) {
			system("mkdir -p /var/smoothwall/mods-available/gkrellmd");
			system("cp -rf * /var/smoothwall/mods-available/gkrellmd/");
			chdir("/var/smoothwall/mods-available/gkrellmd");
		} else {
			print colored("Quitting.  \n", "bold red");
		}
		chdir("usr/local/bin");
		if ((-e "gkrellmd") and (-l "gkrellmd" )) {
			# the link already exists
			print colored("Found a symlink already present.\n", "cyan");
			my $target = readlink("gkrellmd");
			print colored("Got link target: $target\n", "cyan");
			if ($target eq "gkrellmd.$arch") {
				# leave it be
				print color("cyan");
				print <<END;
Link looks ok.  Leaving it alone.  If you notice any 
peculiarities, you should remove the directory and 
re-clone from github.com.
END
				print color('reset');
			} else {
				unlink("gkrellmd");
				system("/bin/ln -snf gkrellmd.$arch gkrellmd");
			}
		} else {
			system("/bin/ln -snf gkrellmd.$arch gkrellmd");
			
		}
		chdir("/var/smoothwall/mods");
		system("/bin/ln -snf ../mods-available/gkrellmd gkrellmd");
		chdir $cwd;
		system("/bin/touch installed");
	}
	default { die colored("Unrecognized installation directory: $cwd", "red"); }
}
